context:
  version: "2.2.0"

package:
  name: stylua
  version: ${{ version }}

source:
  url: https://github.com/JohnnyMorganz/StyLua/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 257863316696fcb868186254c47cef54f80343c66a8bf1430cf24f35add0a475

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - stylua --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Opinionated Lua code formatter
  homepage: https://github.com/JohnnyMorganz/StyLua
  repository: https://github.com/JohnnyMorganz/StyLua

extra:
  recipe-maintainers:
    - danielnachun
