context:
  version: "2.4.1"

package:
  name: stylua
  version: ${{ version }}

source:
  url: https://github.com/JohnnyMorganz/StyLua/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 882eadb417294399a89ba2b3f17edc751d4b6d1892e4814bfbf5c024bb89de6c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - stylua --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Opinionated Lua code formatter
  homepage: https://github.com/JohnnyMorganz/StyLua
  repository: https://github.com/JohnnyMorganz/StyLua

extra:
  recipe-maintainers:
    - danielnachun
